<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="diagramaDeClases" nsURI="http://www.example.org/diagramaDeClases"
    nsPrefix="diagramaDeClases">
  <eClassifiers xsi:type="ecore:EClass" name="Diagrama">
    <eStructuralFeatures xsi:type="ecore:EReference" name="clase_diagrama" upperBound="-1"
        eType="#//Clase" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Clase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombreClase" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="atributo_contenido" upperBound="-1"
        eType="#//Atributo" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operacion_contenida" upperBound="-1"
        eType="#//Operacion" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Atributo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombreAtributo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibilidadAtributo" eType="#//Tipo_Visibilidad"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipoAtributo" eType="#//Tipos_Predefinidos"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operacion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombreOperacion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibilidadOperacion" eType="#//Tipo_Visibilidad"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="retornoOperacion" eType="#//Tipo_Retorno"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Tipo_Visibilidad">
    <eLiterals name="private"/>
    <eLiterals name="protected" value="1"/>
    <eLiterals name="public" value="2"/>
    <eLiterals name="package" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Tipos_Predefinidos">
    <eLiterals name="String"/>
    <eLiterals name="Int" value="1"/>
    <eLiterals name="Double" value="2"/>
    <eLiterals name="boolean" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Tipo_Retorno">
    <eLiterals name="String"/>
    <eLiterals name="Int" value="1"/>
    <eLiterals name="Double" value="2"/>
    <eLiterals name="boolean" value="3"/>
    <eLiterals name="void" value="4"/>
  </eClassifiers>
</ecore:EPackage>
